AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  UserServicesTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${AWS::StackName}-UserServicesTopic
    Metadata:
      StackeryName: UserServicesTopic
    Condition: UserServicesTopicCreateNewResource
  MicroService25:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-MicroService25
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: MicroService25
      CodeUri: src/MicroService25
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
      Events:
        Topic:
          Type: SNS
          Properties:
            Topic: !If
              - UserServicesTopicUseExistingResource
              - !Ref UserServicesTopicExistingResource
              - !Ref UserServicesTopic
    Metadata:
      StackeryName: MicroService25
  UserServicesTopicExistingResource:
    Type: Custom::StackeryExistingResource
    Properties:
      ServiceToken: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:stackery-agent-commander
      Type: topic
      Data: !Ref EnvConfigsnscrudtopicarnAsString
    Condition: UserServicesTopicUseExistingResource
Parameters:
  StackTagName:
    Type: String
    Description: Stack Name (injected by Stackery at deployment time)
  EnvironmentTagName:
    Type: String
    Description: Environment Name (injected by Stackery at deployment time)
  EnvConfigsnscrudtopicarnAsString:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /<EnvironmentName>/sns_crud_topic_arn
Conditions:
  UserServicesTopicCreateNewResource: !Equals
    - 'false'
    - !Ref EnvConfigsnscrudtopicarnAsString
  UserServicesTopicUseExistingResource: !Not
    - Condition: UserServicesTopicCreateNewResource
Metadata:
  EnvConfigParameters:
    EnvConfigsnscrudtopicarnAsString: sns_crud_topic_arn